runmode: release             # 开发模式, debug, release, test
addr: :80                   # HTTP绑定端口
name: apiserver              # API Server的名字
url: http://127.0.0.1:80   # pingServer函数请求的API服务器的ip:port
max_ping_count: 10           # pingServer函数尝试的次数...
log:
  writers: stdout
  logger_level: INFO
  logger_file: log/apiserver.log
  log_format_text: true
  rollingPolicy: size
  log_rotate_date: 1
  log_rotate_size: 10
  log_backup_count: 7